import '../models/user_model.dart';
import '../models/dancer_model.dart';
import '../models/wedding_event_model.dart';
import '../models/organizer_model.dart';
import '../models/mirage_experience_model.dart';
import '../models/booking_model.dart';
import '../models/review_model.dart';
import '../models/notification_model.dart';

class MockData {
  static UserModel currentUser = UserModel(
    id: 'usr_001',
    name: 'Komalpreet Singh',
    email: 'komalpreet@nachoonrent.com',
    phone: '+91 98765 43210',
    location: 'Chandigarh, India',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    bio: 'Passionate about Indian wedding heritage & Baraat celebrations!',
    isVerified: true,
    hasDancerProfile: true,
    dancerProfileId: 'dnc_001',
    hasOrganizerProfile: true,
    organizerProfileId: 'org_001',
    savedDancerIds: ['dnc_002', 'dnc_003'],
    savedEventIds: ['evt_001'],
    savedExperienceIds: ['mrg_001'],
  );

  static List<DancerModel> dancers = [
    DancerModel(
      id: 'dnc_001',
      userId: 'usr_001',
      name: 'Komalpreet & Sher-E-Punjab Troupe',
      avatarUrl: 'https://images.unsplash.com/photo-1545239351-ef35f43d514b?w=400&auto=format&fit=crop&q=80',
      coverVideoThumbnail: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&auto=format&fit=crop&q=80',
      videoUrls: [
        'https://example.com/videos/bhangra_baraat_live.mp4',
        'https://example.com/videos/giddha_performance.mp4'
      ],
      photoGallery: [
        'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1545239351-ef35f43d514b?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&auto=format&fit=crop&q=80',
      ],
      isVerified: true,
      location: 'Chandigarh / Amritsar',
      danceStyles: ['Bhangra', 'Punjabi Folk', 'Giddha', 'Baraat Lead'],
      rating: 4.9,
      reviewCount: 48,
      startingPrice: 25000.0,
      experienceYears: '8+ Years',
      about: 'High-energy authentic Punjabi Bhangra troupe specializing in explosive Baraat entries, Sangeet performances, and international wedding cultural entertainment.',
      isAvailable: true,
      instagramHandle: '@sherepunjab_bhangra',
      youtubeChannel: 'SherEPunjabDancers',
      completedBookings: 64,
      performanceDetails: 'Group of 6 to 12 performers with Dhol players. Props included.',
    ),
    DancerModel(
      id: 'dnc_002',
      userId: 'usr_002',
      name: 'Ananya Sharma Dance Academy',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      coverVideoThumbnail: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80',
      videoUrls: ['https://example.com/videos/bollywood_fusion.mp4'],
      photoGallery: [
        'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=800&auto=format&fit=crop&q=80',
      ],
      isVerified: true,
      location: 'New Delhi / Gurgaon',
      danceStyles: ['Bollywood', 'Semi-Classical', 'Kathak Fusion', 'Contemporary'],
      rating: 4.8,
      reviewCount: 35,
      startingPrice: 35000.0,
      experienceYears: '6 Years',
      about: 'Professional choreography and live dance performance team for luxury Indian Sangeet ceremonies and grand reception galas.',
      isAvailable: true,
      instagramHandle: '@ananya_glam_dance',
      youtubeChannel: 'AnanyaDanceStudio',
      completedBookings: 42,
      performanceDetails: 'Custom choreography for bride & groom plus 4 background dancers.',
    ),
    DancerModel(
      id: 'dnc_003',
      userId: 'usr_003',
      name: 'Padmavati Royal Ghoomar Group',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
      coverVideoThumbnail: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&auto=format&fit=crop&q=80',
      videoUrls: ['https://example.com/videos/rajasthani_ghoomar.mp4'],
      photoGallery: [
        'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=800&auto=format&fit=crop&q=80',
      ],
      isVerified: true,
      location: 'Jaipur / Udaipur',
      danceStyles: ['Rajasthani', 'Ghoomar', 'Kalbelia', 'Folk'],
      rating: 4.95,
      reviewCount: 52,
      startingPrice: 30000.0,
      experienceYears: '10+ Years',
      about: 'Authentic royal Rajasthani folk dancers straight from the heritage palaces of Jaipur and Udaipur. Perfect for Sangeet, Haldi & royal themed weddings.',
      isAvailable: true,
      instagramHandle: '@padmavati_ghoomar',
      youtubeChannel: 'RoyalGhoomarOfficial',
      completedBookings: 89,
      performanceDetails: 'Traditional Poshak attire, fire & pot balancing routines included.',
    ),
    DancerModel(
      id: 'dnc_004',
      userId: 'usr_004',
      name: 'Rangeelo Garba Beats',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
      coverVideoThumbnail: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&auto=format&fit=crop&q=80',
      videoUrls: ['https://example.com/videos/dandiya_night.mp4'],
      photoGallery: [
        'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&auto=format&fit=crop&q=80',
      ],
      isVerified: false,
      location: 'Ahmedabad / Vadodara',
      danceStyles: ['Gujarati', 'Garba', 'Dandiya Raas'],
      rating: 4.7,
      reviewCount: 22,
      startingPrice: 20000.0,
      experienceYears: '5 Years',
      about: 'Vibrant Gujarati Garba and Dandiya team specializing in energetic interactive dance sets for pre-wedding celebrations.',
      isAvailable: true,
      instagramHandle: '@rangeelo_garba_beats',
      youtubeChannel: 'GarbaBeatsOfficial',
      completedBookings: 28,
      performanceDetails: '8 Dancers with traditional Chaniya Choli costume setup.',
    ),
  ];

  static List<WeddingEventModel> weddingEvents = [
    WeddingEventModel(
      id: 'evt_001',
      title: 'Grand Royal Punjabi Wedding & Sangeet Night',
      weddingType: 'Punjabi Wedding',
      description: 'A 3-day royal Punjabi wedding celebration at Forest Hill Resort. Seeking top-tier Bhangra troupe for a high-octane groom Baraat arrival and live Dhol fusion.',
      date: '28 Oct, 2026',
      time: '06:00 PM',
      location: 'Forest Hill Resort, Mohali / Chandigarh',
      organizerId: 'org_001',
      organizerName: 'Komalpreet Events & Co.',
      organizerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      expectedCrowd: 650,
      dancerRequirements: 'Looking for 8 Bhangra dancers with 2 live Dhol players for 2 hours performance.',
      dancersNeeded: 8,
      preferredDanceStyle: 'Bhangra',
      budget: 45000.0,
      coverImageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&auto=format&fit=crop&q=80',
      photos: [
        'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&auto=format&fit=crop&q=80',
      ],
      status: 'published',
      performanceDuration: '2 Hours',
      cancellationRules: 'Full refund up to 7 days prior. 50% refund up to 48 hours prior.',
    ),
    WeddingEventModel(
      id: 'evt_002',
      title: 'Heritage Palace Rajasthani Wedding',
      weddingType: 'Rajasthani Wedding',
      description: 'Palace wedding in Jaipur. Requires Ghoomar & Kalbelia dancers to welcome international and NRI guests during the Royal Welcome Dinner.',
      date: '15 Nov, 2026',
      time: '07:30 PM',
      location: 'Chomu Palace, Jaipur',
      organizerId: 'org_002',
      organizerName: 'Rajwada Wedding Planners',
      organizerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      expectedCrowd: 400,
      dancerRequirements: 'Authentic Rajasthani folk dancers for guest reception and Sangeet ceremony.',
      dancersNeeded: 6,
      preferredDanceStyle: 'Rajasthani',
      budget: 50000.0,
      coverImageUrl: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=800&auto=format&fit=crop&q=80',
      photos: [
        'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=800&auto=format&fit=crop&q=80',
      ],
      status: 'published',
      performanceDuration: '3 Hours',
      cancellationRules: 'Strict 7-day cancellation window.',
    ),
    WeddingEventModel(
      id: 'evt_003',
      title: 'Sangeet & Bollywood Dhamaka Night',
      weddingType: 'Marwari Wedding',
      description: 'Sangeet night requiring energetic Bollywood backup dancers to support family dance acts and bride/groom entry.',
      date: '02 Dec, 2026',
      time: '08:00 PM',
      location: 'The Leela Palace, New Delhi',
      organizerId: 'org_003',
      organizerName: 'Shubh Muhurat Events',
      organizerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
      expectedCrowd: 500,
      dancerRequirements: '4 male and 4 female Bollywood fusion dancers.',
      dancersNeeded: 8,
      preferredDanceStyle: 'Bollywood',
      budget: 60000.0,
      coverImageUrl: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=800&auto=format&fit=crop&q=80',
      photos: [
        'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=800&auto=format&fit=crop&q=80',
      ],
      status: 'published',
      performanceDuration: '2.5 Hours',
      cancellationRules: 'Standard cancellation terms.',
    ),
  ];

  static List<OrganizerModel> organizers = [
    OrganizerModel(
      id: 'org_001',
      userId: 'usr_001',
      name: 'Komalpreet Events & Co.',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
      location: 'Chandigarh & Delhi NCR',
      about: 'Boutique wedding management agency crafting unforgettable big fat Indian weddings across North India.',
      rating: 4.9,
      reviewCount: 31,
      totalEventsOrganized: 45,
      activeEventsCount: 3,
      pastEventPhotos: [
        'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&auto=format&fit=crop&q=80',
      ],
    ),
    OrganizerModel(
      id: 'org_002',
      userId: 'usr_002',
      name: 'Rajwada Wedding Planners',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
      location: 'Jaipur, Rajasthan',
      about: 'Specialized in heritage palace destination weddings, traditional Baraat processions, and cultural guest experiences.',
      rating: 4.95,
      reviewCount: 64,
      totalEventsOrganized: 82,
      activeEventsCount: 5,
      pastEventPhotos: [
        'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=800&auto=format&fit=crop&q=80',
      ],
    ),
  ];

  static List<MirageExperienceModel> mirageExperiences = [
    MirageExperienceModel(
      id: 'mrg_001',
      title: 'Dance in a Live Punjabi Wedding Baraat',
      category: 'Baraat',
      description: 'Join an authentic royal Punjabi wedding procession as an honored guest dancer! Experience the thunderous live Dhol drums, wear traditional turban/dupatta, dance along with the groom entourage, and enjoy authentic wedding cuisine.',
      location: 'Chandigarh / Mohali',
      duration: '4 Hours',
      hostId: 'usr_001',
      hostName: 'Komalpreet Singh',
      hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      pricePerGuest: 4999.0,
      guestCapacity: 10,
      includes: [
        'VIP access pass to live Baraat procession',
        'Traditional wedding turban tied for guests',
        'Live Bhangra workshop before procession starts',
        'Authentic 5-course wedding dinner buffet',
        'Professional photography & video souvenir'
      ],
      excludes: [
        'Hotel accommodation',
        'Personal transportation to venue'
      ],
      guestRules: [
        'Festive Indian ethnic or formal attire required',
        'Respect family tradition & privacy guidelines',
        'Arrive 30 minutes before Baraat assembly'
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1545239351-ef35f43d514b?w=800&auto=format&fit=crop&q=80',
      galleryUrls: [
        'https://images.unsplash.com/photo-1545239351-ef35f43d514b?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&auto=format&fit=crop&q=80',
      ],
      rating: 4.96,
      reviewCount: 29,
      availableDates: ['28 Oct 2026', '05 Nov 2026', '12 Dec 2026'],
      cancellationPolicy: 'Cancel up to 72 hours in advance for full refund.',
    ),
    MirageExperienceModel(
      id: 'mrg_002',
      title: 'Royal Sangeet & Choreography Workshop',
      category: 'Sangeet',
      description: 'Step into a glittering pre-wedding Sangeet evening. Learn iconic Bollywood dance steps with celebrity choreographers and participate in the live celebration.',
      location: 'New Delhi',
      duration: '3 Hours',
      hostId: 'usr_002',
      hostName: 'Ananya Sharma',
      hostAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      pricePerGuest: 3499.0,
      guestCapacity: 15,
      includes: [
        '90-min Bollywood dance masterclass',
        'Entry ticket to Sangeet night gala',
        'Cocktails and royal appetizers'
      ],
      excludes: ['Personal makeup service'],
      guestRules: ['Wear comfortable dance shoes or festive attire'],
      coverImageUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80',
      galleryUrls: [
        'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80',
      ],
      rating: 4.88,
      reviewCount: 18,
      availableDates: ['02 Dec 2026', '18 Dec 2026'],
      cancellationPolicy: 'Standard 48-hour cancellation policy.',
    ),
  ];

  static List<BookingModel> bookings = [
    BookingModel(
      id: 'bk_001',
      type: BookingType.dancer,
      itemId: 'dnc_001',
      itemTitle: 'Komalpreet & Sher-E-Punjab Troupe',
      itemImageUrl: 'https://images.unsplash.com/photo-1545239351-ef35f43d514b?w=400&auto=format&fit=crop&q=80',
      customerId: 'usr_002',
      customerName: 'Ananya Sharma',
      providerId: 'usr_001',
      providerName: 'Komalpreet Singh',
      date: '28 Oct 2026',
      time: '06:00 PM',
      guestCount: 8,
      totalAmount: 25000.0,
      status: BookingStatus.confirmed,
      qrCode: 'NCH-BKG-2026-001',
      specialNotes: 'Dhol drum solo requested at groom entry.',
      createdAt: '2026-09-15',
      isPaid: true,
    ),
    BookingModel(
      id: 'bk_002',
      type: BookingType.mirage,
      itemId: 'mrg_001',
      itemTitle: 'Dance in a Live Punjabi Wedding Baraat',
      itemImageUrl: 'https://images.unsplash.com/photo-1545239351-ef35f43d514b?w=400&auto=format&fit=crop&q=80',
      customerId: 'usr_001',
      customerName: 'Komalpreet Singh',
      providerId: 'usr_002',
      providerName: 'Rajwada Host',
      date: '15 Nov 2026',
      time: '05:30 PM',
      guestCount: 2,
      totalAmount: 9998.0,
      status: BookingStatus.requested,
      qrCode: 'NCH-MRG-2026-002',
      specialNotes: 'Require 2 turbans.',
      createdAt: '2026-09-18',
      isPaid: false,
    ),
  ];

  static List<ReviewModel> reviews = [
    ReviewModel(
      id: 'rev_001',
      bookingId: 'bk_001',
      targetId: 'dnc_001',
      authorName: 'Rohan Malhotra (Organizer)',
      authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
      rating: 5.0,
      comment: 'Unbelievable energy! Komalpreet and his Bhangra troupe made the Baraat procession the highlight of our entire wedding! Highly recommended.',
      date: '10 Sep 2026',
      isVerifiedBooking: true,
    ),
    ReviewModel(
      id: 'rev_002',
      bookingId: 'bk_003',
      targetId: 'mrg_001',
      authorName: 'Sarah Jenkins (USA)',
      authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
      rating: 5.0,
      comment: 'An unforgettable cultural experience! Dancing in an authentic Indian wedding Baraat was a dream come true. Super warm hosts and amazing food!',
      date: '04 Aug 2026',
      isVerifiedBooking: true,
    ),
  ];

  static List<NotificationModel> notifications = [
    NotificationModel(
      id: 'notif_001',
      title: 'Booking Confirmed!',
      body: 'Your dancer booking for Sher-E-Punjab Troupe has been accepted and confirmed.',
      timeAgo: '2 hours ago',
      isRead: false,
      type: 'booking',
      targetId: 'bk_001',
    ),
    NotificationModel(
      id: 'notif_002',
      title: 'Payment Received',
      body: 'Protected payment of ₹25,000 received for event #evt_001.',
      timeAgo: '1 day ago',
      isRead: true,
      type: 'payment',
      targetId: 'bk_001',
    ),
    NotificationModel(
      id: 'notif_003',
      title: 'New Booking Request',
      body: 'Ananya Sharma requested your Mirage Baraat Experience for Nov 15.',
      timeAgo: '2 days ago',
      isRead: true,
      type: 'booking',
      targetId: 'bk_002',
    ),
  ];
}
